class NrcData {
  static const nrcPrefix = <String>[
    '1/',
    '2/',
    '3/',
    '4/',
    '5/',
    '6/',
    '7/',
    '8/',
    '9/',
    '10/',
    '11/',
    '12/',
    '13/',
    '14/'
  ];

  static const regionOne = <String>[
    'AHGAYA',
    'BAMANA',
    'DAPHAYA',
    'HAPANA',
    'KAMANA',
    'KAMATA',
    'KAPATA',
    'KHABADA',
    'KHAPHANA',
    'LAGANA',
    'MAKANA',
    'MAKATA',
    'MAKHABA',
    'MALANA',
    'MAMANA',
    'MANYANA',
    'MASANA',
    'NAMANA',
    'PANADA',
    'PATAAH',
    'PAWANA',
    'SABATA',
    'SADANA',
    'SALANA',
    'SAPABA',
    'TANANA',
    'WAMANA',
    'YABAYA',
    'YAKANA',
  ];

  static const regionTwo = <String>[
    'BALAKHA',
    'DAMASA',
    'LAKANA',
    'MASANA',
    'PHASANA',
    'PHAYASA',
    'YATANA',
    'YATHANA',
  ];

  static const regionThree = <String>[
    'BAAHNA',
    'BAGALA',
    'BATHASA',
    'KADANA',
    'KAKAYA',
    'KAMAMA',
    'KASAKA',
    'LABANA',
    'LATHANA',
    'MAWATA',
    'PAKANA',
    'PHAPANA',
    'SAKALA',
    'THATAKA',
    'WALAMA',
    'YAYATHA'
  ];

  static const regionFour = <String>[
    'HAKHANA',
    'HTATALA',
    'KAKHANA',
    'KAPALA',
    'MATANA',
    'MATAPA',
    'PALAWA',
    'PHALANA',
    'SAMANA',
    'TATANA',
    'TAZANA',
    'YAKHADA',
    'YAZANA'
  ];

  static const regionFive = <String>[
    'AHTANA',
    'AHYATA',
    'BAMANA',
    'BATALA',
    'DAHANA',
    'DAPAYA',
    'HAMALA',
    'HTAKHANA',
    'HTAPAKHA',
    'KABALA',
    'KALAHTA',
    'KALANA',
    'KALATA',
    'KALAWA',
    'KAMANA',
    'KANANA',
    'KATHANA',
    'KHAOUNA',
    'KHAOUTA',
    'KHAPANA',
    'KHATANA',
    'LAHANA',
    'LAYANA',
    'MAKANA',
    'MALANA',
    'MAMANA',
    'MAMATA',
    'MAPALA',
    'MATHANA',
    'MAYANA',
    'NAYANA',
    'PALABA',
    'PALANA',
    'PASANA',
    'PHAPANA',
    'SAKANA',
    'SALAKA',
    'SAMAYA',
    'TAMANA',
    'TASANA',
    'WALANA',
    'WATHANA',
    'YABANA',
    'YAMAPA',
    'YAOUNA'
  ];

  static const regionSix = <String>[
    // "BAPANA",
    // "HTAWANA",
    // "KALAAH",
    // "KASANA",
    // "KATHANA",
    // "KAYAYA",
    // "KHAMAKA",
    // "LALANA",
    // "MAAHNA",
    // "MAAHYA",
    // "MATANA",
    // "PAKAMA",
    // "PALANA",
    // "PALATA"
    "BAPANA",
    "HTAWANA",
    "KALAAH",
    "KASANA",
    "KATHANA",
    "KAYAYA",
    "KHAMAKA",
    "LALANA",
    "MAAHNA",
    "MAAHYA",
    "MAMANA",
    "MATANA",
    "PAKAMA",
    "PALANA",
    "PALATA",
    "TATHAYA",
    "THAYAKHA",
    "YAPHANA",
  ];

  static const regionSeven = <String>[
    // "AHPHANA",
    // "AHTANA",
    // "DAOUNA",
    // "HTATAPA",
    // "KAKANA",
    // "KAPAKA",
    // "KATAKHA",
    // "KAWANA",
    // "MANYANA",
    // "NATALA",
    // "NYALAPA",
    // "PAKHANA",
    // "PAKHATA",
    // "PAMANA",
    // "PATANA",
    // "PATATA",
    // "PHAMANA",
    // "TANGANA",
    // "THAKANA",
    // "THANAPA",
    // "THAWATA",
    // "WAMANA",
    // "YAKANA",
    // "YATANA",
    // "YATAYA",
    // "ZAKANA"
    "AHPHANA",
    "AHTANA",
    "DAOUNA",
    "HTATAPA",
    "KAKANA",
    "KAPAKA",
    "KATAKHA",
    "KAWANA",
    "LAPATA",
    "MALANA",
    "MANYANA",
    "NATALA",
    "NYALAPA",
    "PAKHANA",
    "PAKHATA",
    "PAMANA",
    "PATANA",
    "PATATA",
    "PHAMANA",
    "TANGANA",
    "THAKANA",
    "THANAPA",
    "THAWATA",
    "WAMANA",
    "YAKANA",
    "YATANA",
    "YATAYA",
    "ZAKANA",
  ];

  static const regionEight = <String>[
    // "AHLANA",
    // "GAGANA",
    // "HTALANA",
    // "KAHTANA",
    // "KAMANA",
    // "KHAMANA",
    // "MABANA",
    // "MAKANA",
    // "MALANA",
    // "MAMANA",
    // "MATANA",
    // "MATHANA",
    // "NAMANA",
    // "NGAPHANA",
    // "PAKHAKA",
    // "PAMANA",
    // "PAPHANA",
    // "SALANA",
    // "SAMANA",
    // "SAPAWA",
    // "SAPHANA",
    // "SATAYA",
    // "TATAKA",
    // "THAYANA",
    // "YANAKHA",
    // "YASAKA"
    "AHLANA",
    "GAGANA",
    "HTALANA",
    "KAHTANA",
    "KAMANA",
    "KHAMANA",
    "MABANA",
    "MAHTANA",
    "MAKANA",
    "MALANA",
    "MAMANA",
    "MATANA",
    "MATHANA",
    "NAMANA",
    "NGAPHANA",
    "PAKHAKA",
    "PAMANA",
    "PAPHANA",
    "SALANA",
    "SAMANA",
    "SAPAWA",
    "SAPHANA",
    "SATAYA",
    "TATAKA",
    "THAYANA",
    "YANAKHA",
    "YASAKA"
  ];

  static const regionNine = <String>[
    "AHMAYA",
    "AHMAZA",
    "DAKHATHA",
    "KAPATA",
    "KASANA",
    "KHAAHZA",
    "KHAMASA",
    "LAWANA",
    "MAHAMA",
    "MAHTALA",
    "MAKANA",
    "MAKHANA",
    "MALANA",
    "MAMANA",
    "MANAMA",
    "MANATA",
    "MATAYA",
    "MATHANA",
    "MAYAMA",
    "MAYATA",
    "NAHTAKA",
    "NGATHAYA",
    "NGAZANA",
    "NYAOUNA",
    "OUTATHA",
    "PABANA",
    "PABATHA",
    "PAKAKHA",
    "PAMANA",
    "PAOULA",
    "PATHAKA",
    "SAKANA",
    "SAKATA",
    "TAKANA",
    "TAKATA",
    "TATAOU",
    "TATHANA",
    "THAPAKA",
    "THASANA",
    "WATANA",
    "YAMATHA",
    "ZABATHA",
    "ZAYATHA"
  ];

  static const regionTen = <String>[
    "BALANA",
    "KAHTANA",
    "KAMAYA",
    "KHASANA",
    "KHAZANA",
    "LAMANA",
    "MADANA",
    "MALAMA",
    "PAMANA",
    "THAHTANA",
    "THAPHAYA",
    "YAMANA"
  ];

  static const regionEleven = <String>[
    "AHMANA",
    "BATHATA",
    "GAMANA",
    "KAPHANA",
    "KATALA",
    "KATANA",
    "MAAHNA",
    "MAAHTA",
    "MAOUNA",
    "MAPANA",
    "MAPATA",
    "MATANA",
    "PANAKA",
    "PATANA",
    "SATANA",
    "TAKANA",
    "TAPAWA",
    "THATANA",
    "YABANA",
    "YATHATA"
  ];
  static const regionTwelve = <String>[
    "AHLANA",
    "AHSANA",
    "BAHANA",
    "BATAHTA",
    "DAGAMA",
    "DAGANA",
    "DAGASA",
    "DAGATA",
    "DAGATA",
    "DAGAYA",
    "DALANA",
    "DAPANA",
    "HTATAPA",
    "KAKAKA",
    "KAKHAKA",
    "KAMANA",
    "KAMATA",
    "KAMAYA",
    "KATANA",
    "KATATA",
    "KHAYANA",
    "LAKANA",
    "LAMANA",
    "LAMATA",
    "LATHANA",
    "LATHAYA",
    "MABANA",
    "MAGADA",
    "MAGATA",
    "MAYAKA",
    "OUKATA",
    "OUKATA",
    "PABATA",
    "PAZATA",
    "SAKAKHA",
    "SAKANA",
    "SAKHANA",
    "SAMAHA",
    "TAKANA",
    "TAMANA",
    "TATANA",
    "TATATA",
    "THAGAKA",
    "THAKATA",
    "THAKHANA",
    "THALANA",
    "YAKANA",
    "YAPATHA"
  ];
  static const regionThirdteen = <String>[
    "AHTANA",
    "HAMANA",
    "HAPANA",
    "HAPATA",
    "KAHANA",
    "KAKANA",
    "KAKHANA",
    "KALADA",
    "KALANA",
    "KALATA",
    "KAMANA",
    "KATALA",
    "KATANA",
    "KATATA",
    "KATHANA",
    "KHALANA",
    "KHAYAHA",
    "LAKANA",
    "LAKHANA",
    "LAKHATA",
    "LALANA",
    "LAYANA",
    "MABANA",
    "MABANA",
    "MAHAYA",
    "MAHTANA",
    "MAHTATA",
    "MAKAHTA",
    "MAKANA",
    "MAKATA",
    "MAKHANA",
    "MAKHATA",
    "MALANA",
    "MALATA",
    "MAMAHTA",
    "MAMANA",
    "MAMATA",
    "MANANA",
    "MANATA",
    "MANGANA",
    "MAPANA",
    "MAPATA",
    "MAPHANA",
    "MAPHATA",
    "MASANA",
    "MASATA",
    "MATANA",
    "MATATA",
    "MAYAHTA",
    "MAYANA",
    "MAYATA",
    "NAKHANA",
    "NAKHATA",
    "NAMATA",
    "NAPHANA",
    "NASANA",
    "NATANA",
    "NATAYA",
    "NYAYANA",
    "PALANA",
    "PALATA",
    "PAPAKA",
    "PASANA",
    "PASATA",
    "PATAYA",
    "PAWANA",
    "PAYANA",
    "PHAKHANA",
    "SASANA",
    "TAKANA",
    "TAKHALA",
    "TALANA",
    "TAMANYA",
    "TATANA",
    "TAYANA",
    "THANANA",
    "THAPANA",
    "YANGANA",
    "YASANA"
  ];
  static const regionFourteen = <String>[
    "AHGAPA",
    "AHMANA",
    "AHMATA",
    "BAKALA",
    "DADAYA",
    "DANAPHA",
    "HAKAKA",
    "HATHATA",
    "KAKAHTA",
    "KAKANA",
    "KAKHANA",
    "KALANA",
    "KAPANA",
    "LAMANA",
    "LAPATA",
    "MAAHNA",
    "MAAHPA",
    "MAMAKA",
    "MAMANA",
    "NGAPATA",
    "NGASANA",
    "NGATHAKHA",
    "NGAYAKA",
    "NYATANA",
    "PASALA",
    "PATANA",
    "PATHANA",
    "PATHAYA",
    "PHAPANA",
    "THAPANA",
    "WAKHAMA",
    "YAKANA",
    "YATHAYA",
    "ZALANA"
  ];

  static const List<String> nrcPostfix = [
    '(N)',
    '(E)',
    '(P)',
    '(A)',
    '(F)',
    'TH',
    'G'
  ];
}
